var gamelist = {
	"shell": "https://mathactivity.xyz",
	"1v1": "https://1v1.lol",
	"merczone": "https://merc.zone",
	"zombs": "https://zombsroyale.io",
	"cookie": "https://hotcorn-gamecdn.web.app/cookie/",
	"curvefever": "https://curvefever.pro",
	"ev": "https://ev.io",
	"minecraft": "minecraft.html",
	"repuls": "https://repuls.io",
	"sans": "https://jcw87.github.io/c2-sans-fight/",
	"smashkarts": "https://smashkarts.io",
	"splix": "https://splix.io",
	"gats": "https://gats.io",
	"tetris": "https://tetralegends.app",
	"moomoo": "https://moomoo.io",
	"evoworld": "https://evoworld.io",
	"jklm": "https://jklm.fun",
	"csonline": "https://play-cs.com",
	"tanuki": "https://hotcorn-gamecdn.web.app/tanuki/",
	"ubg100": "https://ubg100.github.io/games.html",
	"totallyscience": "https://actuallymath.com",
	"littlealchemy": "https://littlealchemy.com",
	"emulator": "https://emulatorgames.online/games",
	"linerider": "https://linerider.com",
	"powerline": "https://powerline.io",
	"chromedino": "https://chromedino.com",
	"doodles": "https://www.google.com/doodles",
};

var gamenames = {
	"shell": "Shell Shockers",
	"1v1": "1v1.lol",
	"merczone": "Merc Zone",
	"zombs": "Zombs Royale",
	"cookie": "Cookie Clicker",
	"curvefever": "Curve Fever",
	"ev": "ev.io",
	"minecraft": "WebMC (Minecraft)",
	"repuls": "Repuls",
	"sans": "Sans Bossfight",
	"smashkarts": "Smash Karts",
	"splix": "Splix",
	"gats": "Gats",
	"tetris": "Tetris",
	"moomoo": "MooMoo.io",
	"evoworld": "Evo World",
	"jklm": "BombParty and PopSauce",
	"csonline": "Counter-Strike",
	"tanuki": "Tanuki Sunset",
	"ubg100": "UBG100",
	"totallyscience": "Totally Science",
	"littlealchemy": "Little Alchemy",
	"emulator": "Emulator Games Online",
	"linerider": "Line Rider",
	"powerline": "Powerline",
	"chromedino": "Dinosaur Game",
	"doodles": "Google Doodles",
};

var gameinfo = {
	"tetris": "Tetra Legends, slightly different",
	"ubg100": "Game site featuring additional games",
	"totallyscience": "Game site featuring additional games and chat",
	"emulator": "Old games for emulation",
	"doodles": "All Google Doodles",
};
