var motds = [
    "You should play Terraria",
    "Go do your schoolwork",
    "The proxy is down... again",
    "Try our new theme feature!",
    "Ademay ybay Aughanvay Illimanmay",
    "Try to actually win this time",
    "Life is long, gaming is forever",
    "Cry about it",
    "Math is boring",
    "Go home nerd",
    "Does anyone even look at these?",
    "Did you know you can add custom games?",
    "Inspectlet is cool too",
    "Also try Apple Unblocked",
    "Corn Pr0xy - Now even less GeForce Now compatible!",
    "Select a game... now please",
    "Insert message here",
    "The teacher is probably saying something important right now",
    "People never go outside anymore",
    "You better not be playing on this site at home",
];
