var motds = [
    "Hot Corn Games - Not what you think",
    "You should play Terraria",
    "Go do your schoolwork",
    "The proxy is down... again",
    "Try our new theme feature!",
    "Ademay ybay Aughanvay Illimanmay",
    "Try to actually win this time",
    "Life is long, gaming is forever",
    "Dedicated to Anvitha",
    "Cry about it",
    "Math is boring",
    "Go home nerd",
    "Does anyone even look at these?",
    "Did you know you can add a custom game?",
    "Inspectlet is cool too",
    "Apple Unblocked also exists",
    "Hot Corn Proxy - Now even less GeForce Now compatible!",
    "Select a game... now please",
    "Insert message here",
    "The teacher is probably saying something important right now"
];
